### ISSUE TITLE
fix mysql tests for puppet 4.x - File[~/.my.cnf] and Package[mysql-server]

### ISSUE THREAD

**Issue by czhujer** [SugarFactory/puppet-sugarcrmstack_ng#33]
Failures:

  1) sugarcrmstack_ng supported operating systems on redhat-6-x86_64 sugarcrmstack_ng class with mysql_server_enable should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Parameter path failed on File[~/.my.cnf]: File paths must be fully qualified, not '~/.my.cnf' at /etc/puppet/modules/sugarcrmstack_ng/spec/fixtures/modules/mysql/manifests/server/root_password.pp:31
     # ./spec/classes/main_w_mysql_spec.rb:19:in `block (6 levels) in <top (required)>'

  2) sugarcrmstack_ng supported operating systems on redhat-6-x86_64 sugarcrmstack_ng class with mysql_server_enable should contain Package[mysql-server] with ensure => :present
     Failure/Error: it { is_expected.to contain_package('mysql-server').with(ensure: :present) }
       expected that the catalogue would contain Package[mysql-server] with ensure set to :present but it is set to "installed"
     # ./spec/classes/main_w_mysql_spec.rb:67:in `block (6 levels) in <top (required)>'

  3) sugarcrmstack_ng supported operating systems on redhat-6-x86_64 sugarcrmstack_ng class with mysql_server_enable and _use_pxc => true should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Parameter path failed on File[~/.my.cnf]: File paths must be fully qualified, not '~/.my.cnf' at /etc/puppet/modules/sugarcrmstack_ng/spec/fixtures/modules/mysql/manifests/server/root_password.pp:31
     # ./spec/classes/main_w_mysql_spec.rb:79:in `block (6 levels) in <top (required)>'

  4) sugarcrmstack_ng supported operating systems on redhat-6-x86_64 sugarcrmstack_ng class with mysql_server_enable and _use_pxc => true should contain Package[mysql-server] with ensure => :present
     Failure/Error: it { is_expected.to contain_package('mysql-server').with(ensure: :present) }
       expected that the catalogue would contain Package[mysql-server] with ensure set to :present but it is set to "installed"
     # ./spec/classes/main_w_mysql_spec.rb:127:in `block (6 levels) in <top (required)>'

  5) sugarcrmstack_ng supported operating systems on redhat-7-x86_64 sugarcrmstack_ng class with mysql_server_enable should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Parameter path failed on File[~/.my.cnf]: File paths must be fully qualified, not '~/.my.cnf' at /etc/puppet/modules/sugarcrmstack_ng/spec/fixtures/modules/mysql/manifests/server/root_password.pp:31
     # ./spec/classes/main_w_mysql_spec.rb:19:in `block (6 levels) in <top (required)>'

  6) sugarcrmstack_ng supported operating systems on redhat-7-x86_64 sugarcrmstack_ng class with mysql_server_enable should contain Package[mysql-server] with ensure => :present
     Failure/Error: it { is_expected.to contain_package('mysql-server').with(ensure: :present) }
       expected that the catalogue would contain Package[mysql-server] with ensure set to :present but it is set to "installed"
     # ./spec/classes/main_w_mysql_spec.rb:67:in `block (6 levels) in <top (required)>'

  7) sugarcrmstack_ng supported operating systems on redhat-7-x86_64 sugarcrmstack_ng class with mysql_server_enable and _use_pxc => true should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Parameter path failed on File[~/.my.cnf]: File paths must be fully qualified, not '~/.my.cnf' at /etc/puppet/modules/sugarcrmstack_ng/spec/fixtures/modules/mysql/manifests/server/root_password.pp:31
     # ./spec/classes/main_w_mysql_spec.rb:79:in `block (6 levels) in <top (required)>'

  8) sugarcrmstack_ng supported operating systems on redhat-7-x86_64 sugarcrmstack_ng class with mysql_server_enable and _use_pxc => true should contain Package[mysql-server] with ensure => :present
     Failure/Error: it { is_expected.to contain_package('mysql-server').with(ensure: :present) }
       expected that the catalogue would contain Package[mysql-server] with ensure set to :present but it is set to "installed"
     # ./spec/classes/main_w_mysql_spec.rb:127:in `block (6 levels) in <top (required)>'

**Comment by czhujer** [comment]
solved in https://github.com/SugarFactory/puppet-sugarcrmstack_ng/pull/34
